version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    labels:
      - "no changelog"
      - "area/ci"
  - package-ecosystem: gomod
    directory: /src/go
    schedule:
      interval: weekly
    labels:
      - "area/go"
