# This collector will not appear in documentation, as the go version is preferred,
# /src/go/plugin/go.d/collector/traefik/README.md
#
# meta:
#   plugin_name: python.d.plugin
#   module_name: traefik
#   monitored_instance:
#     name: python.d traefik
#     link: ''
#     categories: []
#     icon_filename: ''
#   related_resources:
#     integrations:
#       list: []
#   info_provided_to_referring_integrations:
#     description: ''
#   keywords: []
#   most_popular: false
# overview:
#   data_collection:
#     metrics_description: ''
#     method_description: ''
#   supported_platforms:
#     include: []
#     exclude: []
#   multi_instance: true
#   additional_permissions:
#     description: ''
#   default_behavior:
#     auto_detection:
#       description: ''
#     limits:
#       description: ''
#     performance_impact:
#       description: ''
# setup:
#   prerequisites:
#     list: []
#   configuration:
#     file:
#       name: ''
#       description: ''
#     options:
#       description: ''
#       folding:
#         title: ''
#         enabled: true
#       list: []
#     examples:
#       folding:
#         enabled: true
#         title: ''
#       list: []
# troubleshooting:
#   problems:
#     list: []
# alerts: []
# metrics:
#   folding:
#     title: Metrics
#     enabled: false
#   description: ""
#   availability: []
#   scopes:
#   - name: global
#     description: ""
#     labels: []
#     metrics:
#     - name: traefik.response_statuses
#       description: Response statuses
#       unit: "requests/s"
#       chart_type: stacked
#       dimensions:
#       - name: success
#       - name: error
#       - name: redirect
#       - name: bad
#       - name: other
#     - name: traefik.response_codes
#       description: Responses by codes
#       unit: "requests/s"
#       chart_type: stacked
#       dimensions:
#       - name: 2xx
#       - name: 5xx
#       - name: 3xx
#       - name: 4xx
#       - name: 1xx
#       - name: other
#     - name: traefik.detailed_response_codes
#       description: Detailed response codes
#       unit: "requests/s"
#       chart_type: stacked
#       dimensions:
#       - name: a dimension for each response code family
#     - name: traefik.requests
#       description: Requests
#       unit: "requests/s"
#       chart_type: line
#       dimensions:
#       - name: requests
#     - name: traefik.total_response_time
#       description: Total response time
#       unit: "seconds"
#       chart_type: line
#       dimensions:
#       - name: response
#     - name: traefik.average_response_time
#       description: Average response time
#       unit: "milliseconds"
#       chart_type: line
#       dimensions:
#       - name: response
#     - name: traefik.average_response_time_per_iteration
#       description: Average response time per iteration
#       unit: "milliseconds"
#       chart_type: line
#       dimensions:
#       - name: response
#     - name: traefik.uptime
#       description: Uptime
#       unit: "seconds"
#       chart_type: line
#       dimensions:
#       - name: uptime
