[package]
name = "journal_reader_ffi"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
error = { path = "../error" }
# journal_reader integrated into journal_file
journal_file = { path = "../journal_file" }
memmap2 = { workspace = true }
serde_json = { workspace = true }
sigbus = { path = "../sigbus" }

[build-dependencies]
cbindgen = "0.28.0"

[lib]
crate-type = ["staticlib"]
