configs:
  - select:
      instrumentation_scope_name: .*hostmetricsreceiver.*networkscraper$
      metric_name: system\.network\.connections
    extract:
      chart_instance_pattern: metric.attributes.protocol
      dimension_name: metric.attributes.state
  - select:
      instrumentation_scope_name: .*hostmetricsreceiver.*networkscraper$
      metric_name: system\.network\.dropped
    extract:
      chart_instance_pattern: metric.attributes.device
      dimension_name: metric.attributes.direction
  - select:
      instrumentation_scope_name: .*hostmetricsreceiver.*networkscraper$
      metric_name: system\.network\.errors
    extract:
      chart_instance_pattern: metric.attributes.device
      dimension_name: metric.attributes.direction
  - select:
      instrumentation_scope_name: .*hostmetricsreceiver.*networkscraper$
      metric_name: system\.network\.io
    extract:
      chart_instance_pattern: metric.attributes.device
      dimension_name: metric.attributes.direction
  - select:
      instrumentation_scope_name: .*hostmetricsreceiver.*networkscraper$
      metric_name: system\.network\.packets
    extract:
      chart_instance_pattern: metric.attributes.device
      dimension_name: metric.attributes.direction
  - select:
      instrumentation_scope_name: .*hostmetricsreceiver.*cpuscraper$
      metric_name: system\.cpu\.time
    extract:
      chart_instance_pattern: metric.attributes.cpu
      dimension_name: metric.attributes.state
  - select:
      instrumentation_scope_name: .*hostmetricsreceiver.*cpuscraper$
      metric_name: system\.cpu\.frequency
    extract:
      chart_instance_pattern: metric.attributes.cpu
  - select:
      instrumentation_scope_name: .*hostmetricsreceiver.*cpuscraper$
      metric_name: system\.cpu\.utilization
    extract:
      chart_instance_pattern: metric.attributes.cpu
      dimension_name: metric.attributes.state
  - select:
      instrumentation_scope_name: .*hostmetricsreceiver.*diskscraper$
      metric_name: system\.disk\.io$
    extract:
      chart_instance_pattern: metric.attributes.device
      dimension_name: metric.attributes.direction
  - select:
      instrumentation_scope_name: .*hostmetricsreceiver.*diskscraper$
      metric_name: system\.disk\.io_time
    extract:
      chart_instance_pattern: metric.attributes.device
  - select:
      instrumentation_scope_name: .*hostmetricsreceiver.*diskscraper$
      metric_name: system\.disk\.merged
    extract:
      chart_instance_pattern: metric.attributes.device
      dimension_name: metric.attributes.direction
  - select:
      instrumentation_scope_name: .*hostmetricsreceiver.*diskscraper$
      metric_name: system\.disk\.operation_time
    extract:
      chart_instance_pattern: metric.attributes.device
      dimension_name: metric.attributes.direction
  - select:
      instrumentation_scope_name: .*hostmetricsreceiver.*diskscraper$
      metric_name: system\.disk\.operations
    extract:
      chart_instance_pattern: metric.attributes.device
      dimension_name: metric.attributes.direction
  - select:
      instrumentation_scope_name: .*hostmetricsreceiver.*diskscraper$
      metric_name: system\.disk\.pending_operations
    extract:
      chart_instance_pattern: metric.attributes.device
  - select:
      instrumentation_scope_name: .*hostmetricsreceiver.*diskscraper$
      metric_name: system\.disk\.weighted_io
    extract:
      chart_instance_pattern: metric.attributes.device
  - select:
      instrumentation_scope_name: .*hostmetricsreceiver.*filesystemscraper$
      metric_name: system\.filesystem\.inodes\.usage
    extract:
      chart_instance_pattern: metric.attributes.mountpoint
      dimension_name: metric.attributes.state
  - select:
      instrumentation_scope_name: .*hostmetricsreceiver.*filesystemscraper$
      metric_name: system\.filesystem\.usage
    extract:
      chart_instance_pattern: metric.attributes.mountpoint
      dimension_name: metric.attributes.state
  - select:
      instrumentation_scope_name: .*hostmetricsreceiver.*filesystemscraper$
      metric_name: system\.filesystem\.utilization
    extract:
      chart_instance_pattern: metric.attributes.mountpoint
  - select:
      instrumentation_scope_name: .*hostmetricsreceiver.*memoryscraper$
      metric_name: system\.memory\.utilization
    extract:
      dimension_name: metric.attributes.state
  - select:
      instrumentation_scope_name: .*hostmetricsreceiver.*pagingscraper$
      metric_name: system\.paging\.faults
    extract:
      dimension_name: metric.attributes.type
  - select:
      instrumentation_scope_name: .*hostmetricsreceiver.*pagingscraper$
      metric_name: system\.paging\.operations
    extract:
      chart_instance_pattern: metric.attributes.type
      dimension_name: metric.attributes.direction
  - select:
      instrumentation_scope_name: .*hostmetricsreceiver.*pagingscraper$
      metric_name: system\.paging\.usage
    extract:
      chart_instance_pattern: metric.attributes.device
      dimension_name: metric.attributes.state
  - select:
      instrumentation_scope_name: .*hostmetricsreceiver.*pagingscraper$
      metric_name: system\.paging\.utilization
    extract:
      chart_instance_pattern: metric.attributes.device
      dimension_name: metric.attributes.state
  - select:
      instrumentation_scope_name: .*hostmetricsreceiver.*processesscraper$
      metric_name: system\.processes\.count
    extract:
      dimension_name: metric.attributes.status
  - select:
      instrumentation_scope_name: .*hostmetricsreceiver.*processscraper$
      metric_name: process\.cpu\.time
    extract:
      dimension_name: metric.attributes.state
  - select:
      instrumentation_scope_name: .*hostmetricsreceiver.*processscraper$
      metric_name: process\.disk\.io
    extract:
      dimension_name: metric.attributes.direction
  - select:
      instrumentation_scope_name: .*hostmetricsreceiver.*processscraper$
      metric_name: process\.context_switches
    extract:
      dimension_name: metric.attributes.type
  - select:
      instrumentation_scope_name: .*hostmetricsreceiver.*processscraper$
      metric_name: process\.cpu\.utilization
    extract:
      dimension_name: metric.attributes.state
  - select:
      instrumentation_scope_name: .*hostmetricsreceiver.*processscraper$
      metric_name: process\.disk\.operations
    extract:
      dimension_name: metric.attributes.direction
  - select:
      instrumentation_scope_name: .*hostmetricsreceiver.*processscraper$
      metric_name: process\.paging\.faults
    extract:
      dimension_name: metric.attributes.type
  - select:
      instrumentation_scope_name: .*hostmetricsreceiver.*processscraper$
      metric_name: process\.paging\.faults
    extract:
      dimension_name: metric.attributes.type
