metrics:
  "system.network.connections":
    - instrumentation_scope:
        name: .*hostmetricsreceiver.*networkscraper$
      dimension_attribute_key: state

  "system.network.dropped":
    - instrumentation_scope:
        name: .*hostmetricsreceiver.*networkscraper$
      dimension_attribute_key: direction

  "system.network.errors":
    - instrumentation_scope:
        name: .*hostmetricsreceiver.*networkscraper$
      dimension_attribute_key: direction

  "system.network.io":
    - instrumentation_scope:
        name: .*hostmetricsreceiver.*networkscraper$
      dimension_attribute_key: direction

  "system.network.packets":
    - instrumentation_scope:
        name: .*hostmetricsreceiver.*networkscraper$
      dimension_attribute_key: direction

  "system.cpu.time":
    - instrumentation_scope:
        name: .*hostmetricsreceiver.*cpuscraper$
      dimension_attribute_key: state

  "system.cpu.frequency":
    - instrumentation_scope:
        name: .*hostmetricsreceiver.*cpuscraper$

  "system.cpu.utilization":
    - instrumentation_scope:
        name: .*hostmetricsreceiver.*cpuscraper$
      dimension_attribute_key: state

  "system.disk.io":
    - instrumentation_scope:
        name: .*hostmetricsreceiver.*diskscraper$
      dimension_attribute_key: direction

  "system.disk.io_time":
    - instrumentation_scope:
        name: .*hostmetricsreceiver.*diskscraper$

  "system.disk.merged":
    - instrumentation_scope:
        name: .*hostmetricsreceiver.*diskscraper$
      dimension_attribute_key: direction

  "system.disk.operation_time":
    - instrumentation_scope:
        name: .*hostmetricsreceiver.*diskscraper$
      dimension_attribute_key: direction

  "system.disk.operations":
    - instrumentation_scope:
        name: .*hostmetricsreceiver.*diskscraper$
      dimension_attribute_key: direction

  "system.disk.pending_operations":
    - instrumentation_scope:
        name: .*hostmetricsreceiver.*diskscraper$

  "system.disk.weighted_io":
    - instrumentation_scope:
        name: .*hostmetricsreceiver.*diskscraper$

  "system.filesystem.inodes.usage":
    - instrumentation_scope:
        name: .*hostmetricsreceiver.*filesystemscraper$
      dimension_attribute_key: state

  "system.filesystem.usage":
    - instrumentation_scope:
        name: .*hostmetricsreceiver.*filesystemscraper$
      dimension_attribute_key: state

  "system.filesystem.utilization":
    - instrumentation_scope:
        name: .*hostmetricsreceiver.*filesystemscraper$

  "system.memory.utilization":
    - instrumentation_scope:
        name: .*hostmetricsreceiver.*memoryscraper$
      dimension_attribute_key: state

  "system.memory.usage":
    - instrumentation_scope:
        name: .*hostmetricsreceiver.*memoryscraper$
      dimension_attribute_key: state

  "system.paging.faults":
    - instrumentation_scope:
        name: .*hostmetricsreceiver.*pagingscraper$
      dimension_attribute_key: type

  "system.paging.operations":
    - instrumentation_scope:
        name: .*hostmetricsreceiver.*pagingscraper$
      dimension_attribute_key: direction

  "system.paging.usage":
    - instrumentation_scope:
        name: .*hostmetricsreceiver.*pagingscraper$
      dimension_attribute_key: state

  "system.paging.utilization":
    - instrumentation_scope:
        name: .*hostmetricsreceiver.*pagingscraper$
      dimension_attribute_key: state

  "system.processes.count":
    - instrumentation_scope:
        name: .*hostmetricsreceiver.*processesscraper$
      dimension_attribute_key: status

  "process.cpu.time":
    - instrumentation_scope:
        name: .*hostmetricsreceiver.*processscraper$
      dimension_attribute_key: state

  "process.disk.io":
    - instrumentation_scope:
        name: .*hostmetricsreceiver.*processscraper$
      dimension_attribute_key: direction

  "process.context_switches":
    - instrumentation_scope:
        name: .*hostmetricsreceiver.*processscraper$
      dimension_attribute_key: type

  "process.cpu.utilization":
    - instrumentation_scope:
        name: .*hostmetricsreceiver.*processscraper$
      dimension_attribute_key: state

  "process.disk.operations":
    - instrumentation_scope:
        name: .*hostmetricsreceiver.*processscraper$
      dimension_attribute_key: direction

  "process.paging.faults":
    - instrumentation_scope:
        name: .*hostmetricsreceiver.*processscraper$
      dimension_attribute_key: type
