[package]
name = "journal_log"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
error = { path = "../error" }
journal_file = { path = "../journal_file" }
memmap2 = { workspace = true }
uuid = { version = "1.0", features = ["v4", "rng"] }

[dev-dependencies]
tempfile = { workspace = true }
