[package]
name = "flatten_otel"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[lints]
workspace = true

[dependencies]
base64 = { workspace = true }
opentelemetry-proto = { workspace = true, features = ["logs", "metrics", "with-serde"] }
flatten-serde-json = { workspace = true }
serde_json = { workspace = true }
tracing = { workspace = true }
