# Ref: https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository#configuring-the-template-chooser
blank_issues_enabled: false
contact_links:
  - name: "Netdata Agent: Question"
    url: https://github.com/netdata/netdata/discussions/new?category=q-a
    about: Ask a question about Netdata Agent
  - name: "Netdata Cloud"
    url: https://github.com/netdata/netdata-cloud/issues/new/choose
    about: Create a report to help us improve our web application
  - name: "Netdata Mobile App"
    url: https://github.com/netdata/netdata-cloud/issues/new/choose
    about: Create a report to help us improve our Mobile App
  - name: Community
    url: https://netdata.cloud/community
    about: If you don't know where to start, visit our community page!
