[workspace]
resolver = "2"
members = [
    "error",
    "journal_file",
    "journal_reader_ffi",
    "journal_log",
    "window_manager",
    "sigbus",
    "otel-plugin",
    "flatten_otel",
    "flog-otel",
]

[workspace.package]
version = "0.1.0"
edition = "2021"

[workspace.dependencies]
memmap2 = "0.9"
zerocopy = { version = "0.9.0-alpha.0", features = ["derive"] }
thiserror = "2"
rand = "0.9"
siphasher = "1.0"
twox-hash = { version = "2.1", default-features = false, features = ["std"] }
static_assertions = "1.1"
duct = "0.13"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
walkdir = "2"
ruzstd = "0.8"
libc = "0.2"
hex = "0.4"
tempfile = "3"
indexmap = "2.9"
uuid = { version = "1.0", features = ["v4", "rng"] }
chrono = { version = "0.4", features = ["serde"] }
tracing = "0.1"
tracing-subscriber = "0.3"

# otel-plugin
prost = "0.13"
regex = "1.10"
tokio = { version = "1.45", features = ["rt-multi-thread", "process", "io-util"] }
tokio-stream = "0.1"
tonic = "0.13"
tonic-build = "0.13"
prost-build = "0.13"
hyper-util = "0.1"
tower = "0.5"
opentelemetry-proto = "0.30"
atty = "0.2"
anyhow = "1.0"
humantime-serde = "1.1"
humantime = "2.2"
bytesize = "1.0"
bytesize-serde = "0.2"

clap = { version = "4.5", features = ["derive", "env"] }

[profile.release]
lto = true
codegen-units = 1
