[package]
name = "netflow-plugin"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[lints]
workspace = true

[[bin]]
name = "netflow-plugin"
path = "src/main.rs"

[dependencies]
anyhow = { workspace = true }
async-trait = { workspace = true }
bytesize = { workspace = true }
bytesize-serde = { workspace = true }
chrono = { workspace = true }
clap = { workspace = true, features = ["derive"] }
foundation = { workspace = true }
journal-common = { workspace = true }
journal-core = { workspace = true }
journal-engine = { workspace = true }
journal-index = { workspace = true }
journal-log-writer = { workspace = true }
journal-registry = { workspace = true }
humantime = { workspace = true }
humantime-serde = { workspace = true }
ipnet = { workspace = true }
netflow_parser = "0.9.0"
notify = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
serde_yaml = { workspace = true }
sflow-parser = "0.6.0"
tokio = { workspace = true }
tokio-util = { workspace = true }
tracing = { workspace = true }
regex = { workspace = true }

rt = { workspace = true }
netdata-plugin-error = { workspace = true }
netdata-plugin-protocol = { workspace = true }

[dev-dependencies]
etherparse = "0.19.0"
pcap-file = "2.0.0"
tempfile = { workspace = true }
