[package]
name = "netdata-plugin-protocol"
version.workspace = true
edition.workspace = true

[lints]
workspace = true

[dependencies]
netdata-plugin-error = { path = "../error" }
netdata-plugin-types = { path = "../types" }

phf = { workspace = true }
atoi = { workspace = true }
tokio-util = { workspace = true }
bytes = { workspace = true }
futures = { workspace = true }
tokio = { workspace = true, features = ["io-std", "io-util"] }
serde = { workspace = true }
serde_json = { workspace = true }
tracing = { workspace = true }

[build-dependencies]
phf_codegen = { workspace = true }

[dev-dependencies]
tokio = { version = "1.0", features = ["full"] }
futures-util = { version = "0.3", features = ["sink"] }
