name: 'Auto Assign'
on: pull_request

jobs:
  auto-assign:
    runs-on: ubuntu-latest
    steps:
      - uses: kentaro-m/auto-assign-action@v1.0.1
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
