name: Dry-run Ingest Check

on:
  pull_request:
    paths:
      - '**/*.md'
      - '**/*.mdx'
      - 'docs/**'
      - '**/metadata.yaml'
      - 'integrations/**'

jobs:
  check-documentation:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout PR branch
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
          path: netdata

      - name: Checkout netdata/learn repository
        uses: actions/checkout@v5
        with:
          repository: netdata/learn
          path: learn

      - name: Init python env
        uses: actions/setup-python@6
        with:
          python-version: "3.9"

      - name: Setup python env
        run: |
          pip install -r learn/.learn_environment/ingest-requirements.txt

      - name: Configure Git to use HTTPS instead of SSH
        run: |
          git config --global url."https://github.com/".insteadOf git@github.com:
          git config --global url."https://".insteadOf git://

      - name: Run Ingest
        env:
          REPO: ${{ github.event.pull_request.head.repo.full_name }}
          BRANCH: ${{ github.event.pull_request.head.ref }}
        run: |
          cd learn
          echo "Running ingest for $REPO:$BRANCH"
          python ingest/ingest.py --repos "$REPO:$BRANCH" --fail-on-netdata
