name: Dry-run Ingest Check

on:
  pull_request:
    paths:
      - '**/*.md'
      - '**/*.mdx'
      - 'docs/**'
      - '**/metadata.yaml'
      - 'integrations/**'

jobs:
  check-documentation:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout PR branch
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
          path: netdata

      - name: Checkout netdata/learn repository
        uses: actions/checkout@v5
        with:
          repository: netdata/learn
          path: learn

      - name: Init python env
        uses: actions/setup-python@v6
        with:
          python-version: "3.9"

      - name: Setup python dependencies
        run: |
          python3 -m venv ./venv
          source ./venv/bin/activate
          pip install -r learn/.learn_environment/ingest-requirements.txt
          cd netdata && ./integrations/pip.sh

      - name: Generate Integrations
        run: |
          source ./venv/bin/activate
          cd netdata && python3 integrations/gen_integrations.py

      - name: Generate Integrations Documentation
        run: |
          source ./venv/bin/activate
          cd netdata && python3 integrations/gen_docs_integrations.py

      - name: Generate src/collectors/COLLECTORS.md
        run: |
          source ./venv/bin/activate
          cd netdata && python3 integrations/gen_doc_collector_page.py

      - name: Run Ingest
        working-directory: learn
        run: |
          source ../venv/bin/activate
          echo "Running ingest with local netdata directory"
          python ingest/ingest.py --local-repo "netdata:${{ github.workspace }}/netdata" --ignore-on-prem-repo --fail-links-netdata
