---
# Handles labelling of PR's.
name: Pull Request Labeler
on:
  schedule:
    - cron: '*/5 * * * *'
jobs:
  labeler:
    runs-on: ubuntu-latest
    steps:
      - uses: docker://docker.io/ilyam8/periodic-pr-labeler:v0.1.0
        if: github.repository == 'netdata/netdata'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          LABEL_MAPPINGS_FILE: .github/labeler.yml
