---
# Handles labelling of PR's.
name: Pull Request Labeler
on:
  pull_request_target: null
concurrency:
  group: pr-label-${{ github.repository_id }}-${{ github.event.pull_request.number }}
  cancel-in-progress: true
jobs:
  labeler:
    name: Apply PR Labels
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: actions/labeler@v5
        if: github.repository == 'netdata/netdata'
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          sync-labels: true
